// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	. "github.com/gitsridhar/myopenapi3/echo/Impl/api/models"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns all fruits
	// (GET /fruits)
	FindFruits(ctx echo.Context, params FindFruitsParams) error
	// Creates a new fruit
	// (POST /fruits)
	AddFruit(ctx echo.Context) error
	// Delete a fruit by ID
	// (DELETE /fruits/{id})
	DeleteFruit(ctx echo.Context, id int64) error
	// Returns a fruit by ID
	// (GET /fruits/{id})
	FindFruitByID(ctx echo.Context, id int64) error
	// Update a fruit by ID
	// (PUT /fruits/{id})
	UpdateFruitByID(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// FindFruits converts echo context to params.
func (w *ServerInterfaceWrapper) FindFruits(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FindFruitsParams
	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameter("form", true, false, "tags", ctx.QueryParams(), &params.Tags)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tags: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FindFruits(ctx, params)
	return err
}

// AddFruit converts echo context to params.
func (w *ServerInterfaceWrapper) AddFruit(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddFruit(ctx)
	return err
}

// DeleteFruit converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteFruit(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteFruit(ctx, id)
	return err
}

// FindFruitByID converts echo context to params.
func (w *ServerInterfaceWrapper) FindFruitByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FindFruitByID(ctx, id)
	return err
}

// UpdateFruitByID converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateFruitByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateFruitByID(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/fruits", wrapper.FindFruits)
	router.POST(baseURL+"/fruits", wrapper.AddFruit)
	router.DELETE(baseURL+"/fruits/:id", wrapper.DeleteFruit)
	router.GET(baseURL+"/fruits/:id", wrapper.FindFruitByID)
	router.PUT(baseURL+"/fruits/:id", wrapper.UpdateFruitByID)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWTXPbNhD9K5htj6yoOpkeeKoT2TOaaZ1O3fSS6gATSxEt8eEFaIWj4X/vACAlW6Sc",
	"pO100uYkCtwF3u57+8A9lEZZo1F7B8UeXFmj4vHxishQeLBkLJKXGJdLIzD8CnQlSeul0VCkYBbfZVAZ",
	"UtxDAVL7FxeQge8spr+4RYI+A4XO8e3ZjcbXh1TnSeot9H0GhPetJBRQvIPhwDF802dwTa30YV/eNG8q",
	"KN7t4WvCCgr4Kj/Wmg+F5je4Sxl9dlqpFFN4b7W8b5FJwUzFfI2sislPa/7u5UzNJ8ilgE0f8B4ATDqt",
	"uZpp0A1XeHr4SZMy8Hw7zfylsx/KPAEZEWz6sCx1ZRL92vMyokXFZROSSYqyMa34fhtWFqVRkA3o4Zak",
	"qDmxX1H/wcOJLYWc2nvrijw/5MasPjuBfMkuf1ozX3PPBCqjnSfu0SX4zHlDyELLeIh3kEEjS9QOj+2D",
	"S8vLGtnFYjk5fLfbLXh8vTC0zYdcl/+wfn11c3v1zcViuai9amJHkZR7U90iPcgSz1WQx7A8NFb6JoT9",
	"2LFIL7sNYCGDBySXivt2sVwsw97GouZWQgEv4lIGlvs6aiCPlcbHLfoppz+jb0k7xpsmNSX0xqjIcWzP",
	"bxriAalFawEFXEstrtO24STiCj2Si6PydHfPt455wyrZeCR210EQAhRw3yJ1R5JDHGSDecTR8agi6Kky",
	"0wIn4l3473wX+xTmJ87gUwSKv5eqVUy36g4pqJfQtY2PsCgWfwZTI1VU+BHUB22p3wT5O2uCCkLGxXI5",
	"ah51MhVrG1nGXua/uwBxP1f2c44z2s1JK/qJ+JPIR0BpOCreNv6TMD0HJVn8zNGtxvcWS4+C4RCTgWuV",
	"4tTNqi6gs8bNKPQ1YRxZzjTuhsGV+ijQBVu1CX8IIgybmh2KiWwvRVItJI9C518Z0f1jvTheBNN2pAn2",
	"hnEhws8BPDz2S08t9n9TQR8hnP+SUGbIjxGDreV7KfokmQb9zGW3iuuMMyf1thmuLXbXsfWKWTIPUswI",
	"JSWNWnnW4NarYCnVSO8AYzCUYMJHP5FiQvY5c5m//6fm8nJacIKScIjPickDE48oCPiev5XGaO5QMKOP",
	"RK5X56+lV118+ynEVejL+l/j7Yse6Qm3oxJsO6OEt1bwx7L5GCGknL8qhTZm//+0MNT1GSnhlNskhBiD",
	"9DCS9fSTuzElb2rjfB4+ePtN/2cAAAD//wLyfQOBDgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
