// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package models

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Fruit defines model for Fruit.
type Fruit struct {
	// Id Unique id of the fruit
	Id int64 `json:"id"`

	// Name Name of the fruit
	Name string `json:"name"`

	// Tag Type of the fruit
	Tag *string `json:"tag,omitempty"`
}

// NewFruit defines model for NewFruit.
type NewFruit struct {
	// Name Name of the fruit
	Name string `json:"name"`

	// Tag Type of the fruit
	Tag *string `json:"tag,omitempty"`
}

// FindFruitsParams defines parameters for FindFruits.
type FindFruitsParams struct {
	// Tags tags to filter by
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddFruitJSONRequestBody defines body for AddFruit for application/json ContentType.
type AddFruitJSONRequestBody = NewFruit
